name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '14'


    - name: Install dependencies
      working-directory: ./app
      run: npm install

    - name: Run tests
      working-directory: ./app
      run: npm test

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' # Only apply on main branch
      run: terraform apply -auto-approve

    - name: Save Terraform Outputs
      id: terraform_outputs
      run: |
        echo "::set-env name=OUTPUT_VAR_NAME::$(terraform output -raw your_output_variable_name)"

    - name: Export Terraform Outputs
      run: |
        echo $OUTPUT_VAR_NAME >> $GITHUB_ENV
